name: Automate Site Updates

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-site:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install gspread google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client openpyxl pandas

    - name: Run Python Script
      env:
        GOOGLE_CLOUD_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
      run: |
        python ./Schedule_V3.py

    - name: Commit and Push Changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name 'ChessBadger'
        git config --global user.email 'clarklas831@gmail.com'
        git add .
        git commit -m "Automated site update"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/ChessBadger/Admin_Schedule.git HEAD:main
